include:
  - project: base/ci-cd
    file: python.yml
    ref: main

variables:
  PROJECT_DISPLAY_NAME: Thompson Finance Backend
  DEPLOY_BASE_PATH: backend

docker-build:
  extends: .docker_build_template

deploy:
  extends: .deploy_template

success:
  extends: .notify_success_template

failure:
  extends: .notify_failure_template
